#!/bin/bash

# 复制安装文件
mv ${OPENSHIFT_REPO_DIR}php/install/index.php ${OPENSHIFT_REPO_DIR}php/install/index.php.bak
cp -rf ${OPENSHIFT_REPO_DIR}.openshift/tools/install.php ${OPENSHIFT_REPO_DIR}php/install/index.php
cp -rf ${OPENSHIFT_REPO_DIR}.openshift/tools/deploy.sh ${OPENSHIFT_REPO_DIR}php/install/deploy.sh